### ISSUE TITLE
  angularjs-dropdown-multiselect#1.5.2 is not compatible with Angular 1.5

### ISSUE THREAD

**Issue by rhgithub1** [dotansimha/angularjs-dropdown-multiselect#212]
My Current Angular version is 1.5.

$ bower install angularjs-dropdown-multiselect --save
bower angularjs-dropdown-multiselect#\*           cached https://github.com/dotansimha/angularjs-dropdown-multiselect.git#1.5.2
bower angularjs-dropdown-multiselect#\*         validate 1.5.2 against https://github.com/dotansimha/angularjs-dropdown-multiselect.git#*
bower angular#~1.2.0                             cached https://github.com/angular/bower-angular.git#1.2.29
bower angular#~1.2.0                           validate 1.2.29 against https://github.com/angular/bower-angular.git#~1.2.0
bower lodash#~2.4.1                              cached https://github.com/lodash/lodash.git#2.4.2
bower lodash#~2.4.1                            validate 2.4.2 against https://github.com/lodash/lodash.git#~2.4.1
bower angular#~1.x                               cached https://github.com/angular/bower-angular.git#1.5.0
bower angular#~1.x                             validate 1.5.0 against https://github.com/angular/bower-angular.git#~1.x
**bower                                         ECONFLICT Unable to find suitable version for angular**

**Comment by Machadalo** [comment]
Facing the same issue my angular version is 1.4

**Comment by pkempenaers** [comment]
Hi @Machadalo I've fixed this and some other things on a fork (for example no more lodash dependency).
You can install that fork using 
`bower install myforce-angular-dropdown-multiselect`

The documentation for that specific fork can be found [here](http://myforce.github.io/angularjs-dropdown-multiselect/#/). You'll also find a link to that fork there, we're maintaining that fork so you'll probably get a quicker response if you create an issue there.

**Comment by Machadalo** [comment]
Hi @Pieter I tried installing by
bower install myforce-angular-dropdown-multiselect

It is still showing me error ENOTFOUND Package
myforce-angular-dropdown-multiselect not found.

Could please help me in resolving this


On Fri, Mar 11, 2016 at 1:48 PM, Pieter Kempenaers <notifications@github.com
